kind: pipeline
type: exec
name: Judge-Girl/Judge-Girl-Web

steps:
  - name: Build
    commands:
      - npm install
      - npm run build
  - name: Build Docker Image
    commands:
      - docker build . -t judge-girl-web
    when:
      branch:
        - master
      event:
        - push
  - name: Deploy
    commands:
      - docker stop judge-girl-web || echo "Judge-Girl-Web doesn't exist, start launching..."
      - docker run --rm -d -p 4200:80 --name judge-girl-web judge-girl-web
    when:
      branch:
        - master
      event:
        - push
